# User & SSH configuration.

## Root
- name: Change default password of root user
  user:
    name: root
    state: present
    password: "{{ root_password | password_hash('sha512') }}"  # Password must be encrypted for Linux hosts
  
## Admin user
- name: Create an admin user with sudo privileges
  user:
    name: "{{ admin_user_name }}"
    groups: "sudo"
    append: yes # don't remove other groups
    state: present
    password: "{{ admin_password | password_hash('sha512') }}"  # Password must be encrypted for Linux hosts
    shell: "/bin/bash"

- name: Add authorized key for admin user
  authorized_key:
    user: "{{ admin_user_name }}"
    state: present
    key: "{{ lookup('file', admin_user_key_path) }}"

## Deployment user
- name: Create a deployment user with sudo privileges
  user:
    name: "{{ deployment_user_name }}"
    groups: "sudo"
    append: yes # don't remove other groups
    state: present
    password: "{{ deployment_password | password_hash('sha512') }}"  # Password must be encrypted for Linux hosts
    shell: "/bin/bash"

- name: Add authorized key for deployment user
  authorized_key:
    user: "{{ deployment_user_name }}"
    state: present
    key: "{{ lookup('file', deployment_user_key_path) }}"

## Site user
- name: Create site user
  user:
    name: "{{ site_user }}"
    system: yes   # system account without home dir
    shell: /sbin/nologin # forbid logging in
    state: present

### Ensure site user is present in his primary group
### (for some reason, this was not the case after)
### NOTE: this command needs to be tested
- name: Ensure site user is added to his primary group
  user:
    name: "{{ site_user }}"
    groups: "{{ site_user }}"
    append: yes # don't remove other groups

## SSH configuration
- name: Update config of SSH service
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "{{ item.find }}"
    line: "{{ item.replace }}"
  loop:
    - { find: '^(# *)?PermitRootLogin (yes|no)', replace: 'PermitRootLogin no' }

- name: Restart sshd
  service:
    name: sshd
    state: restarted
