# fail2ban installation & configuration
# (by default fail2ban monitors SSH logs & bans for 10 minutes IPs with 5 failed login attempts)
- name: Install fail2ban
  apt:
    state: present
    update_cache: true
    pkg: fail2ban

- name: Start & Enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: true
