deployment_user_name: "{{ lookup('env', 'DEPLOYMENT_USER_NAME') }}"
hex_chars: '0123456789ABCDEF'

backup_local_folder: "{{ lookup('env', 'BACKUP_LOCAL_FOLDER') }}"
backup_remote_folder: "{{ lookup('env', 'REMOTE_TEMP_FOLDER') }}/backup"
backup_db_dump_filename: "{{ lookup('env', 'BACKUP_DB_DUMP_FILENAME') }}"
backup_db_dump_filename_suffix: "{{ query('community.general.random_string', upper=false, lower=false, override_special=hex_chars, numbers=false)[0] }}"
# backup_db_dump_filepath: "/{{ backup_db_dump_filename }}_{{ backup_db_dump_filename_suffix }}"  # variable is set as a fact in the tasks.yml to avoid multiple evalutations of `backup_db_dump_filename_suffix`
backup_db_max_backup_count: "{{ lookup('env', 'BACKUP_DB_MAX_BACKUP_COUNT') }}"

backend_setting_db_database_host: "{{ lookup('env', 'BACKEND_SETTING_DB_DATABASE_HOST') }}"
backend_setting_db_database_port: "{{ lookup('env', 'BACKEND_SETTING_DB_DATABASE_PORT') }}"
backend_setting_db_init_username: "{{ lookup('env', 'BACKEND_SETTING_DB_INIT_USERNAME') }}"
backend_setting_db_init_password: "{{ lookup('env', 'BACKEND_SETTING_DB_INIT_PASSWORD') }}"
backend_setting_db_database: "{{ lookup('env', 'BACKEND_SETTING_DB_DATABASE') }}"
