current_username: "{{ lookup('env', 'USER') }}"

env_file: "{{ lookup('env', 'ENV_FILE') }}"
project_root_directory: "{{ playbook_dir | dirname }}"
python_interpreter_path: "{{ playbook_dir | dirname }}/venv/bin/python"
