{
 "title": "02. Auth",
 "tags": [ "Site Monitoring" ],
 "time": { "from": "now-60d/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "logs_db", "label": "Logs DB", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "Server Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily Server Logins",
   "type": "timeseries",
   "description": "Daily Number of Authorizations Recorded in wtmp files",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n\trecord_time::DATE as \"Date\",\n\tCOUNT(*) AS \"Number of Logins\"\nFROM server_auth_logs\nWHERE\nrecord_time >= '${__from:date}' AND record_time <= '${__to:date}'\n-- record_time BETWEEN '2023-01-13' AND '2023-02-12'\nGROUP BY record_time::DATE"
    }
   ]
  },
  {
   "title": "Suspicious Logins",
   "type": "timeseries",
   "description": "Daily Number of Authorizations Recorded in wtmp files from unknown IPs",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n\trecord_date as \"Date\",\n\tCASE WHEN logins_from_unknown_ips = 0 THEN NULL ELSE logins_from_unknown_ips END AS \"Logins From Unknown IPs\" -- Nullify zero values to avoid drawing them\nFROM (\n\tSELECT\n\t\trecord_date,\n\t\tCOUNT(*) AS logins_from_unknown_ips\n\tFROM (\n\t\tSELECT\n\t\t\trecord_time::DATE as record_date\n\t\tFROM server_auth_logs\n\t\tLEFT JOIN (\n\t\t\tSELECT\n\t\t\t\tremote,\n\t\t\t\tlogin_date\n\t\t\tFROM known_ips \n\t\t\tWHERE \n\t\t\t\t(login_date >= '${__from:date}'::DATE - 7 AND login_date <= '${__to:date}'::DATE + 7)\n\t\t\t\t-- login_date BETWEEN '2023-01-13' AND '2023-02-12'\t\n\t\t) known_ips_over_period\n\t\tON server_auth_logs.remote = known_ips_over_period.remote\n\t\tAND server_auth_logs.record_time::DATE - known_ips_over_period.login_date BETWEEN -7 AND 7\n\t\tWHERE \n\t\t(record_time >= '${__from:date}' AND record_time <= '${__to:date}')\n\t\t-- record_time BETWEEN '2023-01-13' AND '2023-02-12'\n\t\tAND known_ips_over_period.remote IS NULL\n\t) logins_from_unknown_ips\n\tGROUP BY record_date\n) result_with_zero_values"
    }
   ]
  },
  {
   "title": "Logins per User",
   "type": "table",
   "description": "Total number of logins per user over period",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n\t\"user\" as \"User\",\n\tCOUNT(*) AS \"Num of Logins\",\n\tMAX(record_time) AS \"Last Logged In\"\nFROM server_auth_logs\nWHERE\nrecord_time >= '${__from:date}' AND record_time <= '${__to:date}'\n-- record_time BETWEEN '2023-01-13' AND '2023-02-12'\nGROUP BY \"user\""
    }
   ]
  },
  {
   "title": "Logins with ut_type = 0",
   "type": "stat",
   "description": "Total number of logins with zero ut_type (deleted wtmp record) over period",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(*) AS \"Number of Logins\"\nFROM server_auth_logs\nWHERE (\n(record_time >= '${__from:date}' AND record_time <= '${__to:date}')\n-- (record_time BETWEEN '2023-01-13' AND '2023-02-12')\nOR record_time = '1970-01-01 00:00:00'\n)\nAND ut_type = 0"
    }
   ]
  },
  { "title": "Fail2Ban", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Failed Logins",
   "type": "timeseries",
   "description": "Daily number of failed login attermps",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  record_time::DATE AS \"Date\",\n  COUNT(*) AS \"Number of Failed Logins\"\nFROM fail2ban_logs \nWHERE\n  (record_time >= '${__from:date}' AND record_time <= '${__to:date}')\n\t-- record_time BETWEEN '2023-01-13' AND '2023-02-12'\n  AND event_type = 'Found'\nGROUP BY record_time::DATE"
    }
   ]
  },
  {
   "title": "Bans",
   "type": "timeseries",
   "description": "Daily number of IP bans",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  record_time::DATE AS \"Date\",\n  COUNT(*) AS \"Number of Bans\"\nFROM fail2ban_logs \nWHERE\n  (record_time >= '${__from:date}' AND record_time <= '${__to:date}')\n\t-- record_time BETWEEN '2023-01-13' AND '2023-02-12'\n  AND event_type = 'Ban'\nGROUP BY record_time::DATE"
    }
   ]
  },
  { "title": "Site Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Site Logins",
   "type": "timeseries",
   "description": "Daily number of successful logins over the  period",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n\trecord_time::DATE AS \"Date\",\n\tCOUNT(*) AS \"Number of Site Logins\"\nFROM app_access_logs\nWHERE\n\trecord_time >= '${__from:date}' AND record_time <= '${__to:date}'\n\t-- record_time BETWEEN '2023-01-08' AND '2023-02-12'\n\tAND path = '/auth/login'\n\tAND status = 200\nGROUP BY record_time::DATE"
    }
   ]
  },
  {
   "title": "Failed Site Logins",
   "type": "timeseries",
   "description": "Daily number of failed logins, excluding blocked attempts, over the  period",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n\trecord_time::DATE AS \"Date\",\n\tCOUNT(*) AS \"Number of Site Logins\"\nFROM app_access_logs\nWHERE\n\trecord_time >= '${__from:date}' AND record_time <= '${__to:date}'\n\t-- record_time BETWEEN '2023-01-08' AND '2023-02-12'\n\tAND path = '/auth/login'\n\tAND status = 401\nGROUP BY record_time::DATE"
    },
    {
     "rawSql": "SELECT\n\trecord_time::DATE AS \"Date\",\n\tCOUNT(*) AS \"Number of Site Logins\"\nFROM app_access_logs\nWHERE\n\trecord_time >= '${__from:date}' AND record_time <= '${__to:date}'\n\t-- record_time BETWEEN '2023-01-08' AND '2023-02-12'\n\tAND path = '/auth/login'\n\tAND status = 401\nGROUP BY record_time::DATE"
    }
   ]
  },
  { "title": "Navigation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  { "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 } }
 ]
}