{
 "title": "01. Healthcheck",
 "tags": [ "Site Monitoring" ],
 "time": { "from": "now-60d/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "logs_db", "label": "Logs DB", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Since Update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - execution_time)) / 60)::INTEGER AS \"Time Since Update\"\nFROM healthcheck"
    }
   ]
  },
  {
   "title": "Ping Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE\n    WHEN server_reachable THEN 'OK'\n    ELSE 'Failed'\n  END as \"Ping Status\"\nFROM healthcheck"
    }
   ]
  },
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN backend_status = 'active' THEN 'OK'\n    ELSE backend_status\n  END as \"Backend Status\"  \nFROM healthcheck"
    }
   ]
  },
  {
   "title": "DB Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE\n    WHEN postgresql_status = 'active' THEN 'OK'\n    ELSE postgresql_status\n  END as \"DB Status\"\nFROM healthcheck"
    }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE\n    WHEN nginx_status = 'active' THEN 'OK'\n    ELSE nginx_status\n  END as \"Nginx Status\"\nFROM healthcheck"
    }
   ]
  },
  {
   "title": "Days until SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  EXTRACT(DAY FROM (ssl_expiry_time - CURRENT_TIMESTAMP)) AS \"Days until SSL Expiration\"\nFROM healthcheck"
    }
   ]
  },
  { "title": "Server Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  cpu_usage as \"CPU Usage\",\n  memory_used as \"Memory Used\",\n  memory_available as \"Memory Available\",\n  memory_available::FLOAT / memory_total as \"Memory Available, %\",\n  memory_swap as \"Swap Size\",\n  memory_total as \"Memory Total\",\n  disk_used as \"Disk Used\",\n  disk_total as \"Disk Total\",\n  (disk_total - disk_used)::FLOAT / disk_total as \"Disk Available, %\"\nFROM healthcheck"
    }
   ]
  },
  { "title": "Log Fetching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "description": "Number of jobs, which weren't successfully finished during last execution",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\n    CASE \n      WHEN last_execution_status != 'success' THEN 1\n      ELSE 0\n    END\n  ) as \"Number of Failed Jobs\"\nFROM fetch_jobs_status "
    }
   ]
  },
  {
   "title": "Not Recently Run",
   "type": "stat",
   "description": "Number of jobs, which were last executed more than an hour ago",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\n    CASE \n      WHEN CURRENT_TIMESTAMP - last_execution_time > INTERVAL '1 hour' THEN 1\n      ELSE 0\n    END\n  ) as \"Number of Jobs not Recently Run\"\nFROM fetch_jobs_status "
    }
   ]
  },
  {
   "title": "No Recent Full Fetch",
   "type": "stat",
   "description": "Number of jobs, which didn't successfully run a full fetch during the last 2 days",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\n    CASE \n      WHEN CURRENT_TIMESTAMP - last_successful_full_fetch_time > INTERVAL '48 hour' THEN 1\n      ELSE 0\n    END\n  ) as \"Number of Jobs without Recent Full Fetch\"\nFROM fetch_jobs_status "
    }
   ]
  },
  { "title": "Site Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Time Since Last Execution",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (EXTRACT(EPOCH FROM (\n    CURRENT_TIMESTAMP - COALESCE(MAX(record_time), TIMESTAMP '1970-01-01')\n  )))::INTEGER / 60 AS \"Time Since Last Execution\"\nFROM backup_script_logs \nWHERE event_source = 'main' AND message = 'Finished script execution.'"
    }
   ]
  },
  {
   "title": "Time Since DB Backup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (EXTRACT(EPOCH FROM (\n    CURRENT_TIMESTAMP - COALESCE(MAX(record_time), TIMESTAMP '1970-01-01')\n  )))::INTEGER / 60 AS \"Time Since Database Backup\"\nFROM backup_script_logs \nWHERE event_source = 'backup_db' AND message = 'Finished database backup.'"
    }
   ]
  },
  {
   "title": "Last DB Backup Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN message = 'Existing backup with recent modify time found, exiting.' THEN 'Skipped'\n    WHEN message = 'No internet connection available.' THEN 'No internet'\n    WHEN message = 'Internet connection is metered, exiting.' THEN 'Metered connection'\n    WHEN message = 'Production server is currently unreachable.' THEN 'Server unreachable'\n    WHEN message LIKE '%Database backup execution finished with a non-zero exit code%' THEN 'Error'\n    WHEN message = 'Finished database backup.' THEN 'Success'\n\tWHEN message IS NULL THEN 'No data'\n    ELSE 'Unknown'\n  END as status\nFROM (\n  SELECT\n    message\n  FROM backup_script_logs\n  WHERE event_source = 'backup_db'\n  AND record_time IN (\n    SELECT\n      MAX(record_time) as record_time\n    FROM backup_script_logs \n    WHERE event_source = 'backup_db'\n  )\n  UNION ALL -- add a second line no data case\n  SELECT NULL as message\n) msg\nLIMIT 1\n"
    }
   ]
  },
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Logins from Unknown Addresses",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tAVG(login_count) AS \"Avg Daily Logins\",\n\tMAX(login_count) AS \"Max Daily Logins\"\n\nFROM (\n\tSELECT\n\t\tcalendar_dates.d AS date,\n\t\tCOALESCE(login_count, 0) AS login_count\n\tFROM (\n\t\tSELECT \n\t\t\trecord_time::DATE AS login_date,\n\t\t\tCOUNT(DISTINCT server_auth_logs.record_id) AS login_count\n\t\tFROM server_auth_logs\n\n\t\tLEFT JOIN known_ips\t\t-- known_ips keeps unique pairs of login_date + remote\n\t\tON server_auth_logs.remote = known_ips.remote\n\t\tAND login_date - known_ips.login_date BETWEEN -7 AND 7\n\n\t\tWHERE\n\t\t\trecord_time >= '${__from:date}' AND record_time <= '${__to:date}'\n\t\t\tAND known_ips.remote IS NULL\n\n\t\tGROUP BY record_time::DATE\n\n\t\tORDER BY login_date\n\t) login_count_by_date\t\t-- Get daily count of logins from unknown ips\n\n\tRIGHT JOIN (\n\t\tSELECT calendar_dates::date AS d\n\t\tFROM GENERATE_SERIES(\n\t\t'${__from:date:YYYY-MM-DD}'::DATE,\n\t\t'${__to:date:YYYY-MM-DD}'::DATE,\n\t\t'1 day'::INTERVAL\n\t\t) calendar_dates\n\t) calendar_dates\t-- Generate all dates for query period and join dailt login counts to them\n\tON calendar_dates.d = login_count_by_date.login_date\n\n) calendar_login_dates"
    }
   ]
  },
  {
   "title": "Fail2ban Summary",
   "type": "table",
   "gridPos": { "h": 3, "w": 10, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tAVG(COALESCE(failed_logins_count, 0)) AS \"Avg Daily Failed Logins\",\n\tAVG(COALESCE(bans_count, 0)) AS \"Avg Daily Bans\",\n\tMAX(failed_logins_count) AS \"Max Daily Failed Logins\",\n\tMAX(bans_count) AS \"Max Daily Bans\"\nFROM (\n\tSELECT\n\t\tevent_date,\n\t\tSUM(CASE WHEN event_type = 'Found' THEN event_count ELSE 0 END) AS failed_logins_count,\n\t\tSUM(CASE WHEN event_type = 'Ban' THEN event_count ELSE 0 END) AS bans_count\n\tFROM (\n\t\tSELECT\n\t\t\trecord_time::DATE AS event_date,\n\t\t\tevent_type,\n\t\t\tCOUNT(*) AS event_count\n\t\tFROM fail2ban_logs\n\t\tWHERE record_time >= '${__from:date}' AND record_time <= '${__to:date}'\n\t\tGROUP BY \n\t\t\trecord_time::DATE,\n\t\t\tevent_type\n\t) daily_events_count_multiline\n\n\tGROUP BY event_date\n) daily_events_count\n\nRIGHT JOIN (\n\tSELECT calendar_dates::date AS d\n\tFROM GENERATE_SERIES(\n\t'${__from:date:YYYY-MM-DD}'::DATE,\n\t'${__to:date:YYYY-MM-DD}'::DATE,\n\t'1 day'::INTERVAL\n\t) calendar_dates\n) calendar_dates\t-- Generate all dates for query period and join dailt login counts to them\nON calendar_dates.d = daily_events_count.event_date"
    }
   ]
  },
  {
   "title": "Site Logins",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tAVG(COALESCE(number_of_failed_logins, 0)) AS \"Avg Daily Failed Logins\",\n\tMAX(number_of_failed_logins) AS \"Max Daily Failed Logins\"\nFROM (\n\tSELECT\n\t\trecord_time::DATE AS record_date,\n\t\tCOUNT(*) AS number_of_failed_logins\n\tFROM app_access_logs\n\tWHERE\n\t\trecord_time >= '${__from:date}' AND record_time <= '${__to:date}'\n\t\t-- record_time BETWEEN '2023-01-08' AND '2023-02-11'\n\t\tAND path = '/auth/login'\n\t\tAND status = 401\n\tGROUP BY record_time::DATE\n) failed_logins_by_date\nRIGHT JOIN (\n\tSELECT calendar_dates::date AS d\n\tFROM GENERATE_SERIES(\n\t'${__from:date:YYYY-MM-DD}'::DATE,\n\t'${__to:date:YYYY-MM-DD}'::DATE,\n\t-- '2023-01-08',\n\t-- '2023-02-11',\n\t'1 day'::INTERVAL\n\t) calendar_dates\n) calendar_dates\t-- Generate all dates for query period and join dailt login counts to them\nON calendar_dates.d = failed_logins_by_date.record_date"
    }
   ]
  },
  { "title": "Backend Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Backend Errors",
   "type": "stat",
   "description": "Total number of requests processed by site backend with 500+ response code over the period",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  -- record_time::DATE as \"Date\",\n  COUNT(*) AS \"Number of Errors\"\nFROM app_access_logs\nWHERE\n  record_time >= '${__from:date}' AND record_time <= '${__to:date}'\n  AND status >= 500\n-- GROUP BY record_time::DATE"
    }
   ]
  },
  {
   "title": "Failed DB Jobs",
   "type": "stat",
   "description": "Number of scheduled database jobs, which failed during their last execution",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(\n\t\tCASE\n\t\t\tWHEN number_of_error_lines > 0 THEN 1 ELSE 0\n  \t\tEND\n\t) AS \"Number of Failed Scheduled Jobs\"\nFROM (\n\tSELECT\n\t\tjob_type,\n\t\tSUM(\n\t\t\tCASE\n\t\t\t\tWHEN level = 'ERROR' THEN 1 ELSE 0\n\t   \t\tEND\n\t\t) AS number_of_error_lines\n\tFROM (\n\t\tSELECT\n\t\t\tdatabase_scheduled_jobs_logs.job_type AS job_type,\n\t\t\tdatabase_scheduled_jobs_logs.level AS level\n\t\tFROM database_scheduled_jobs_logs\n\t\tINNER JOIN (\n\t\t\tSELECT\n\t\t\t\tjob_type,\n\t\t\t\tMAX(record_time) AS record_time\n\t\t\tFROM database_scheduled_jobs_logs\n\t\t\tWHERE\n\t\t\t\trecord_time >= '${__from:date}' AND record_time <= '${__to:date}'\n\t\t\t\t-- record_time BETWEEN '2023-01-13' AND '2023-02-12'\n\t\t\tGROUP BY job_type\n\t\t) as max_timestamps\n\t\tON database_scheduled_jobs_logs.record_time = max_timestamps.record_time\n\t\tAND database_scheduled_jobs_logs.job_type = max_timestamps.job_type\n\t) last_records_per_job_type\n\tGROUP BY job_type\n) error_lines_per_job_type"
    }
   ]
  },
  { "title": "Nagivation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 } }
 ]
}