{
 "title": "04. Log Fetching & Backups",
 "tags": [ "Site Monitoring" ],
 "time": { "from": "now-60d/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "execution_id",
    "label": "Execution ID",
    "query": "SELECT DISTINCT execution_id FROM fetch_jobs_logs\nWHERE record_time >= '${__from:date}' AND record_time <= '${__to:date}'"
   },
   { "name": "logs_db", "label": "Logs DB", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "Job Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  job_name as \"Job Name\",\n  last_execution_id as \"Last Execution ID\",\n  last_execution_status as \"Last Execution Status\",\n  (EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - last_execution_time)) / 60)::INTEGER AS \"Time Since Last Execution\",\n  (EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - last_successful_full_fetch_time)) / 60)::INTEGER AS \"Time Since Last Full Fetch\"\nFROM fetch_jobs_status "
    }
   ]
  },
  { "title": "Site Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Time Since Last Execution",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (EXTRACT(EPOCH FROM (\n    CURRENT_TIMESTAMP - COALESCE(MAX(record_time), TIMESTAMP '1970-01-01')\n  )))::INTEGER / 60 AS \"Time Since Last Execution\"\nFROM backup_script_logs \nWHERE event_source = 'main' AND message = 'Finished script execution.'"
    }
   ]
  },
  {
   "title": "Time Since DB Backup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (EXTRACT(EPOCH FROM (\n    CURRENT_TIMESTAMP - COALESCE(MAX(record_time), TIMESTAMP '1970-01-01')\n  )))::INTEGER / 60 AS \"Time Since Database Backup\"\nFROM backup_script_logs \nWHERE event_source = 'backup_db' AND message = 'Finished database backup.'"
    }
   ]
  },
  {
   "title": "Last DB Backup Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN message = 'Database backup is disabled.' THEN 'Disabled'\n    WHEN message = 'Existing backup with recent modify time found, exiting.' THEN 'Skipped'\n    WHEN message = 'Database backup was performed recently, exiting.' THEN 'Skipped'\n    WHEN message = 'No internet connection available.' THEN 'No internet'\n    WHEN message = 'Internet connection is metered, exiting.' THEN 'Metered connection'\n    WHEN message = 'Production server is currently unreachable.' THEN 'Server unreachable'\n    WHEN message LIKE '%Database backup execution finished with a non-zero exit code%' THEN 'Error'\n    WHEN message = 'Finished database backup.' THEN 'Success'\n\tWHEN message IS NULL THEN 'No data'\n    ELSE 'Unknown'\n  END as status\nFROM (\n  SELECT\n    message\n  FROM backup_script_logs\n  WHERE event_source = 'backup_db'\n  AND record_id IN (\n    SELECT\n      MAX(record_id) as record_id\n    FROM backup_script_logs \n    WHERE event_source = 'backup_db'\n  )\n  UNION ALL -- add a second line no data case\n  SELECT NULL as message\n) msg\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Time Since File Backup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (EXTRACT(EPOCH FROM (\n    CURRENT_TIMESTAMP - COALESCE(MAX(record_time), TIMESTAMP '1970-01-01')\n  )))::INTEGER / 60 AS \"Time Since Database Backup\"\nFROM backup_script_logs \nWHERE event_source = 'backup_static_files' AND message = 'Finished static files backup.'"
    }
   ]
  },
  {
   "title": "Last File Backup Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN message = 'Static files backup is disabled.' THEN 'Disabled'\n    WHEN message = 'Static files backup was performed recently, exiting.' THEN 'Skipped'\n    WHEN message = 'No internet connection available.' THEN 'No internet'\n    WHEN message = 'Internet connection is metered, exiting.' THEN 'Metered connection'\n    WHEN message = 'Production server is currently unreachable.' THEN 'Server unreachable'\n    WHEN message LIKE '%Static files backup execution finished with a non-zero exit code%' THEN 'Error'\n    WHEN message = 'Finished static files backup.' THEN 'Success'\n\t  WHEN message IS NULL THEN 'No data'\n    ELSE 'Unknown'\n  END as status\nFROM (\n  SELECT\n    message\n  FROM backup_script_logs\n  WHERE event_source = 'backup_static_files'\n  AND record_id IN (\n    SELECT\n      MAX(record_id) as record_id\n    FROM backup_script_logs \n    WHERE event_source = 'backup_static_files'\n  )\n  UNION ALL -- add a second line no data case\n  SELECT NULL as message\n) msg\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Fetch Jobs Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT\n  record_time as \"Time\",\n  execution_id as \"Execution ID\",\n  job_name as \"Job Name\",\n  level as Level,\n  message as Message\nFROM fetch_jobs_logs\nWHERE\n  record_time >= '${__from:date}' AND record_time <= '${__to:date}'\n  AND (\n    '_ALL' in ($execution_id) -- Don't filter by execution_id field, if all IDs are selected\n    OR execution_id IN ($execution_id)\n  )\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Site Backup Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": "SELECT\n  record_time as \"Time\",\n  event_source as \"Event Source\",\n  level as Level,\n  message as Message\nFROM backup_script_logs \nWHERE\n  record_time >= '${__from:date}' AND record_time <= '${__to:date}'\n"
      }
     ]
    }
   ]
  },
  { "title": "Nagivation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  { "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 } }
 ]
}