{
 "title": "03. Requests and Scheduled Jobs",
 "tags": [ "Site Monitoring" ],
 "time": { "from": "now-60d/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "response_status",
    "label": "Status",
    "query": "SELECT DISTINCT status FROM nginx_access_logs\nWHERE record_time >= '${__from:date}' AND record_time <= '${__to:date}'"
   },
   {
    "name": "request_id",
    "label": "Request id",
    "query": "SELECT DISTINCT request_id FROM app_access_logs\nWHERE record_time >= '${__from:date}' AND record_time <= '${__to:date}'\nAND status IN ($response_status)"
   },
   {
    "name": "request_path",
    "label": "Request path",
    "query": "SELECT DISTINCT path FROM app_access_logs\nWHERE record_time >= '${__from:date}' AND record_time <= '${__to:date}'\nAND status IN ($response_status)"
   },
   { "name": "logs_db", "label": "Logs DB", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily Requests",
   "type": "timeseries",
   "description": "Daily number of requests processed by backend over the period.\nCan be filtered by path and response status code.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n\trecord_time::DATE AS \"Date\",\n\tCOUNT(*) AS \"Daily Number of Requests\"\nFROM app_access_logs\nWHERE\n\t(record_time >= '${__from:date}' AND record_time <= '${__to:date}')\n\t-- record_time BETWEEN '2023-01-08' AND '2023-02-12'\n\tAND status IN ($response_status)\n\tAND path IN ($request_path)\nGROUP BY record_time::DATE"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "timeseries",
   "description": "Avg, min and max request processing timings groupped by day.\nCan be filtered by request path & response status.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n\trecord_time::DATE AS \"Date\",\n\tAVG(elapsed_time) AS \"Average Time\",\n\tMAX(elapsed_time) AS \"Max Time\",\n\tMIN(elapsed_time) AS \"Min Time\"\nFROM app_access_logs\nWHERE\n\t(record_time >= '${__from:date}' AND record_time <= '${__to:date}')\n\t-- record_time BETWEEN '2023-01-08' AND '2023-02-12'\n\tAND status IN ($response_status)\n\tAND path IN ($request_path)\nGROUP BY record_time::DATE"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Daily number of requests with server-side error response statuses.\nCan be filtered by request path & response status.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n\trecord_time::DATE AS \"Date\",\n\tCOUNT(*) AS \"Daily Number of Errors\"\nFROM app_access_logs\nWHERE\n\t(record_time >= '${__from:date}' AND record_time <= '${__to:date}')\n\t-- record_time BETWEEN '2023-01-08' AND '2023-02-12'\n\tAND status >= 500\n\tAND status IN ($response_status)\n\tAND path IN ($request_path)\nGROUP BY record_time::DATE"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Daily Requests",
   "type": "timeseries",
   "description": "Daily number of requests processed by Nginx over the period.\nCan be filtered by path and response status code.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n\trecord_time::DATE AS \"Date\",\n\tCOUNT(*) AS \"Daily Number of Requests\"\nFROM nginx_access_logs\nWHERE\n\t(record_time >= '${__from:date}' AND record_time <= '${__to:date}')\n\t-- record_time BETWEEN '2023-01-08' AND '2023-02-12'\n\tAND status IN ($response_status)\n\tAND path IN ($request_path)\nGROUP BY record_time::DATE"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Daily number of records in Nginx error log",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n\trecord_time::DATE AS \"Date\",\n\tCOUNT(*) AS \"Daily Number of Errors\"\nFROM nginx_error_logs \nWHERE\n\t(record_time >= '${__from:date}' AND record_time <= '${__to:date}')\n\t-- record_time BETWEEN '2023-01-08' AND '2023-02-12'\nGROUP BY record_time::DATE"
    }
   ]
  },
  { "title": "Scheduled Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Failed DB Jobs",
   "type": "stat",
   "description": "Number of scheduled database jobs, which failed during their last execution",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(\n\t\tCASE\n\t\t\tWHEN number_of_error_lines > 0 THEN 1 ELSE 0\n  \t\tEND\n\t) AS \"Number of Failed Scheduled Jobs\"\nFROM (\n\tSELECT\n\t\tjob_type,\n\t\tSUM(\n\t\t\tCASE\n\t\t\t\tWHEN level = 'ERROR' THEN 1 ELSE 0\n\t   \t\tEND\n\t\t) AS number_of_error_lines\n\tFROM (\n\t\tSELECT\n\t\t\tdatabase_scheduled_jobs_logs.job_type AS job_type,\n\t\t\tdatabase_scheduled_jobs_logs.level AS level\n\t\tFROM database_scheduled_jobs_logs\n\t\tINNER JOIN (\n\t\t\tSELECT\n\t\t\t\tjob_type,\n\t\t\t\tMAX(record_time) AS record_time\n\t\t\tFROM database_scheduled_jobs_logs\n\t\t\tWHERE\n\t\t\t\trecord_time >= '${__from:date}' AND record_time <= '${__to:date}'\n\t\t\t\t-- record_time BETWEEN '2023-01-13' AND '2023-02-12'\n\t\t\tGROUP BY job_type\n\t\t) as max_timestamps\n\t\tON database_scheduled_jobs_logs.record_time = max_timestamps.record_time\n\t\tAND database_scheduled_jobs_logs.job_type = max_timestamps.job_type\n\t) last_records_per_job_type\n\tGROUP BY job_type\n) error_lines_per_job_type"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  job_type AS \"Job Type\",\n  (EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - MAX(record_time))) / 60)::INTEGER AS \"Time Since Last Execution\"\nFROM database_scheduled_jobs_logs \nWHERE\n  record_time >= '${__from:date}' AND record_time <= '${__to:date}'\n\t-- record_time BETWEEN '2023-01-08' AND '2023-02-12'\nGROUP BY job_type"
    }
   ]
  },
  {
   "title": "Backend Access Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\n  record_time AS \"Time\",\n  request_id AS \"Request ID\",\n  remote AS \"Remote\",\n  \"path\" AS \"Path\",\n  method AS \"Method\",\n  status AS \"Status\",\n  user_agent AS \"User Agent\",\n  referer AS \"Referer\"\nFROM app_access_logs \nWHERE\n  record_time >= '${__from:date}' AND record_time <= '${__to:date}'\n  AND status IN ($response_status)\n  AND path IN ($request_path)\n  AND (\n    '_ALL' in ($request_id) -- Don't filter by request_id field, if all IDs are selected\n    OR request_id IN ($request_id)\n  )\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Event Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT\n  record_time AS \"Time\",\n  request_id AS \"Request ID\",\n  level AS \"Level\",\n  event_type AS \"Event Type\",\n  message AS \"Message\",\n  details as Details\nFROM app_event_logs \nWHERE\n  record_time >= '${__from:date}' AND record_time <= '${__to:date}'\n  AND (\n    '_ALL' in ($request_id) -- Don't filter by request_id field, if all IDs are selected\n    OR request_id IN ($request_id)\n  )\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx Access Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT\n  record_time AS \"Time\",\n  remote AS \"Remote\",\n  \"path\" AS \"Path\",\n  method AS \"Method\",\n  status AS \"Status\",\n  body_bytes_sent AS \"Body Size\",\n  user_agent AS \"User Agent\",\n  referer AS \"Referer\",\n  request AS \"Request\"\nFROM nginx_access_logs \nWHERE\n  record_time >= '${__from:date}' AND record_time <= '${__to:date}'\n  AND status IN ($response_status)\n  AND path IN ($request_path)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx Error Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT\n  record_time AS \"Time\",\n  level AS \"Level\",\n  message AS \"Message\"\nFROM nginx_error_logs \nWHERE\n  record_time >= '${__from:date}' AND record_time <= '${__to:date}'\n  -- AND status IN ($response_status)\n  -- AND path IN ($request_path)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduled Jobs Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": "SELECT\n  record_time AS \"Time\",\n  job_type AS \"Job type\",\n  level AS \"Level\",\n  message AS \"Message\"\nFROM database_scheduled_jobs_logs \nWHERE\n  record_time >= '${__from:date}' AND record_time <= '${__to:date}'\n"
      }
     ]
    }
   ]
  },
  { "title": "Navigation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  { "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 } }
 ]
}