# Removes automatic site backup on local machine.


- name: Remove backup script logrotate config
  file:
    path: /etc/logrotate.d/site_backup
    state: absent
  become: yes

- name: Remove cron file for automatic backup execution & related jobs
  file:
    path: /etc/cron.d/site_backup
    state: absent
  become: yes
