# Schedules automatic site backup on local machine.
# Requires sudo privileges on local machine and prompts for password when started.
- hosts: localhost
  connection: local
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
      unsafe: yes
  roles:
    - backup_schedule
