# Executes backup-related roles.
# Mainly used by a local cronjob running backup script.
- hosts: srv
  roles:
    - { role: backup_db, tags: [backup_db] }
    - { role: backup_static_files, tags: [backup_static_files] }

