# Deploys frontend & backend on a single machine behind Nginx.
# SSL certificate & key must be placed on the maching separately.
- hosts: srv
  roles:
    - frontend_deploy
    - backend
    - backend_scheduled
    - nginx
    - ufw
