# Initial configuration & security setup of the deployment server:
# - installs & configures UFW;
# - installs & configures fail2ban for SSH bruteforce prevention;
# - installs miscellaneous packages;
# - configures root, deployment and site users and SSH service.
#
# NOTE: when running playbook against a known host after it was reset to a clean state, it's SSH key must be updated in known hosts file:
# 1) Remove known host info:
#       ssh-keygen -R $ANSIBLE_HOST
# 2) Manually connect to the server & add its key.
     

- hosts: srv
  roles:
    - server_config_ufw
    - server_config_fail2ban
    - server_config_misc
    - server_config_users_and_ssh