# Updates backend on an existing single machine deployment.
- hosts: srv
  roles:
    - backend_update_on_start
    - backup_db
    - backend_deploy
    - backend_scheduled
    - backend_update_on_finish
