# Updates backend on an existing single machine deployment.
- hosts: srv
  roles:
    - backend_update_on_start
    - db_backup
    - backend_deploy
    - backend_scheduled
    - backend_update_on_finish
