"""App access and event logs

Revision ID: 2731ea067903
Revises: 
Create Date: 2023-01-20 01:31:16.287192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import FetchedValue


# revision identifiers, used by Alembic.
revision = '2731ea067903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_access_log',
    sa.Column('record_id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=8), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('elapsed_time', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('remote', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_app_access_log'))
    )
    op.create_index(op.f('ix_app_access_log_path'), 'app_access_log', ['path'], unique=False)
    op.create_index(op.f('ix_app_access_log_record_time'), 'app_access_log', ['record_time'], unique=False)
    op.create_index(op.f('ix_app_access_log_request_id'), 'app_access_log', ['request_id'], unique=False)
    op.create_index(op.f('ix_app_access_log_status'), 'app_access_log', ['status'], unique=False)
    op.create_table('app_event_log',
    sa.Column('record_id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=8), nullable=True),
    sa.Column('level', sa.String(length=8), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_app_event_log'))
    )
    op.create_index(op.f('ix_app_event_log_record_time'), 'app_event_log', ['record_time'], unique=False)
    op.create_index(op.f('ix_app_event_log_request_id'), 'app_event_log', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_event_log_request_id'), table_name='app_event_log')
    op.drop_index(op.f('ix_app_event_log_record_time'), table_name='app_event_log')
    op.drop_table('app_event_log')
    op.drop_index(op.f('ix_app_access_log_status'), table_name='app_access_log')
    op.drop_index(op.f('ix_app_access_log_request_id'), table_name='app_access_log')
    op.drop_index(op.f('ix_app_access_log_record_time'), table_name='app_access_log')
    op.drop_index(op.f('ix_app_access_log_path'), table_name='app_access_log')
    op.drop_table('app_access_log')
    # ### end Alembic commands ###
