"""Site backup logs table

Revision ID: 2e6ea493b416
Revises: 5c8744dcc3c1
Create Date: 2023-02-05 22:03:28.058549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import FetchedValue


# revision identifiers, used by Alembic.
revision = '2e6ea493b416'
down_revision = '5c8744dcc3c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_script_logs',
    sa.Column('record_id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=True),
    sa.Column('event_source', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_backup_script_logs'))
    )
    op.create_index(op.f('ix_backup_script_logs_record_time'), 'backup_script_logs', ['record_time'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE backup_script_logs ALTER record_id ADD GENERATED BY DEFAULT AS IDENTITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_script_logs_record_time'), table_name='backup_script_logs')
    op.drop_table('backup_script_logs')
    # ### end Alembic commands ###
