"""Server auth logs and known IPs tables

Revision ID: 3a5ca57e6a5b
Revises: e55355564d0d
Create Date: 2023-02-02 14:03:37.138794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import FetchedValue


# revision identifiers, used by Alembic.
revision = '3a5ca57e6a5b'
down_revision = 'e55355564d0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('known_ips',
    sa.Column('record_id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('login_date', sa.Date(), nullable=False),
    sa.Column('remote', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_known_ips'))
    )
    op.create_index(op.f('ix_known_ips_login_date'), 'known_ips', ['login_date'], unique=False)
    op.create_index('ix_known_ips_remote_login_date', 'known_ips', ['remote', 'login_date'], unique=True)
    op.create_table('server_auth_logs',
    sa.Column('record_id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ut_type', sa.SmallInteger(), nullable=True),
    sa.Column('user', sa.Text(), nullable=True),
    sa.Column('remote', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_server_auth_logs'))
    )
    op.create_index(op.f('ix_server_auth_logs_record_time'), 'server_auth_logs', ['record_time'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE known_ips ALTER record_id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute("ALTER TABLE server_auth_logs ALTER record_id ADD GENERATED BY DEFAULT AS IDENTITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_auth_logs_record_time'), table_name='server_auth_logs')
    op.drop_table('server_auth_logs')
    op.drop_index('ix_known_ips_remote_login_date', table_name='known_ips')
    op.drop_index(op.f('ix_known_ips_login_date'), table_name='known_ips')
    op.drop_table('known_ips')
    # ### end Alembic commands ###
