"""Healthcheck table

Revision ID: 5c8744dcc3c1
Revises: 20728f3c683f
Create Date: 2023-02-04 19:30:21.309717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8744dcc3c1'
down_revision = '20728f3c683f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcheck',
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_reachable', sa.Boolean(), nullable=True),
    sa.Column('nginx_status', sa.Text(), nullable=True),
    sa.Column('backend_status', sa.Text(), nullable=True),
    sa.Column('postgresql_status', sa.Text(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_used', sa.BigInteger(), nullable=True),
    sa.Column('memory_available', sa.BigInteger(), nullable=True),
    sa.Column('memory_swap', sa.BigInteger(), nullable=True),
    sa.Column('memory_total', sa.BigInteger(), nullable=True),
    sa.Column('disk_used', sa.BigInteger(), nullable=True),
    sa.Column('disk_total', sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healthcheck')
    # ### end Alembic commands ###
