"""Fetch jobs logs table

Revision ID: 9c950c9dd9b4
Revises: d404fd6ad6b4
Create Date: 2023-01-27 23:48:16.420357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import FetchedValue


# revision identifiers, used by Alembic.
revision = '9c950c9dd9b4'
down_revision = 'd404fd6ad6b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_jobs_logs',
    sa.Column('record_id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_id', sa.String(length=8), nullable=True),
    sa.Column('job_name', sa.String(length=32), nullable=True),
    sa.Column('level', sa.String(length=8), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_fetch_jobs_logs'))
    )
    op.create_index(op.f('ix_fetch_jobs_logs_record_time'), 'fetch_jobs_logs', ['record_time'], unique=False)
    op.alter_column('fetch_jobs_status', 'last_execution_id',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###
    op.execute("ALTER TABLE fetch_jobs_logs ALTER record_id ADD GENERATED BY DEFAULT AS IDENTITY")


def downgrade() -> None:
    op.execute("ALTER TABLE fetch_jobs_logs ALTER record_id DROP IDENTITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fetch_jobs_status', 'last_execution_id',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.drop_index(op.f('ix_fetch_jobs_logs_record_time'), table_name='fetch_jobs_logs')
    op.drop_table('fetch_jobs_logs')
    # ### end Alembic commands ###
