"""Database scheduled jobs

Revision ID: b755771b5e94
Revises: 2731ea067903
Create Date: 2023-01-21 13:45:06.351760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import FetchedValue


# revision identifiers, used by Alembic.
revision = 'b755771b5e94'
down_revision = '2731ea067903'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_scheduled_jobs',
    sa.Column('record_id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('job_type', sa.String(length=64), server_default=FetchedValue(), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id', 'job_type', name=op.f('pk_database_scheduled_jobs'))
    )
    op.create_index(op.f('ix_database_scheduled_jobs_record_time'), 'database_scheduled_jobs', ['record_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_database_scheduled_jobs_record_time'), table_name='database_scheduled_jobs')
    op.drop_table('database_scheduled_jobs')
    # ### end Alembic commands ###
