"""Fetch jobs status table

Revision ID: d404fd6ad6b4
Revises: 84d8e799506f
Create Date: 2023-01-26 14:37:05.461863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd404fd6ad6b4'
down_revision = '84d8e799506f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_jobs_status',
    sa.Column('job_name', sa.String(length=32), nullable=False),
    sa.Column('last_execution_id', sa.String(length=8), nullable=False),
    sa.Column('last_execution_status', sa.String(length=32), nullable=False),
    sa.Column('last_execution_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_successful_full_fetch_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_name', name=op.f('pk_fetch_jobs_status'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fetch_jobs_status')
    # ### end Alembic commands ###
