"""Nginx error logs table

Revision ID: e55355564d0d
Revises: e8f36d3ae355
Create Date: 2023-01-31 00:08:21.284484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import FetchedValue


# revision identifiers, used by Alembic.
revision = 'e55355564d0d'
down_revision = 'e8f36d3ae355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nginx_error_logs',
    sa.Column('record_id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_nginx_error_logs'))
    )
    op.create_index(op.f('ix_nginx_error_logs_record_time'), 'nginx_error_logs', ['record_time'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE nginx_error_logs ALTER record_id ADD GENERATED BY DEFAULT AS IDENTITY")


def downgrade() -> None:
    op.execute("ALTER TABLE nginx_error_logs ALTER record_id DROP IDENTITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nginx_error_logs_record_time'), table_name='nginx_error_logs')
    op.drop_table('nginx_error_logs')
    # ### end Alembic commands ###
