"""SSL expiry time column in healthcheck

Revision ID: ec02e8ff02bc
Revises: 2e6ea493b416
Create Date: 2023-02-05 23:50:19.485710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec02e8ff02bc'
down_revision = '2e6ea493b416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('healthcheck', sa.Column('ssl_expiry_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('healthcheck', 'ssl_expiry_time')
    # ### end Alembic commands ###
